# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ClassZ Agile
email: wayne.hetherington@classz.ca
description: > # this means to ignore newlines until "baseurl:"
  Want to add some class to your Agile efforts?
  Wayne can help you with all your Agile needs:
   - Team Building
   - Scrum, Kanban, Scaling
   - Coaching
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://classz.ca" # the base hostname & protocol for your site
twitter_username: 
github_username: waynehet

# Build settings
markdown: kramdown
